import { User } from "../src/utils/types";


export const usersMockData: User[] = [
    {
        id: '1a2b3c',
        fullName: 'Ada Lovelace',
        email: 'ada.lovelace@example.com',
        phoneNumber: '+1-555-1234',
        bvn: '12345678901',
        gender: 'Female',
        maritalStatus: 'Single',
        children: '0',
        residenceType: 'Apartment',
        educationLevel: 'Master’s Degree',
        employmentStatus: 'Employed',
        sector: 'Technology',
        durationEmployment: '3 years',
        officeEmail: 'ada.lovelace@techcorp.com',
        monthlyIncome: '₦500,000 - ₦700,000',
        loanRepayment: 15000,
        savings: 120000,
        twitter: '@ada_lovelace',
        facebook: 'facebook.com/ada.lovelace',
        instagram: '@adalovelace',
        guarantors: [
            {
                fullName: 'Charles Babbage',
                phoneNumber: '+1-555-5678',
                email: 'charles.babbage@example.com',
                relationship: 'Friend',
            },
        ],
        tier: 2,
        balance: 350000,
        bank: 'First National Bank',
        accountNumber: 1234567890,
        bankId: 'FNB001',
        status: 'Active',
        organization: 'TechCorp Inc.',
        username: 'adal',
        dateJoined: '2023-07-15T10:20:30Z',
    },
    {
        id: '4d5e6f',
        fullName: 'Grace Hopper',
        email: 'grace.hopper@example.com',
        phoneNumber: '+1-555-2345',
        bvn: '10987654321',
        gender: 'Female',
        maritalStatus: 'Married',
        children: '2',
        residenceType: 'House',
        educationLevel: 'PhD',
        employmentStatus: 'Employed',
        sector: 'Defense',
        durationEmployment: '10 years',
        officeEmail: 'grace.hopper@navy.gov',
        monthlyIncome: '₦800,000 - ₦1,000,000',
        loanRepayment: 25000,
        savings: 500000,
        twitter: '@gracehopper',
        facebook: 'facebook.com/grace.hopper',
        instagram: '@gracehopper',
        guarantors: [
            {
                fullName: 'Howard Aiken',
                phoneNumber: '+1-555-6789',
                email: 'howard.aiken@example.com',
                relationship: 'Colleague',
            },
            {
                fullName: 'Jean Bartik',
                phoneNumber: '+1-555-9876',
                email: 'jean.bartik@example.com',
                relationship: 'Friend',
            },
        ],
        tier: 3,
        balance: 750000,
        bank: 'United Bank',
        accountNumber: 9876543210,
        bankId: 'UBN002',
        status: 'Active',
        organization: 'US Navy',
        username: 'ghopper',
        dateJoined: '2022-03-01T08:15:00Z',
    },
    {
        id: '7g8h9i',
        fullName: 'Alan Turing',
        email: 'alan.turing@example.com',
        phoneNumber: '+1-555-3456',
        bvn: '11223344556',
        gender: 'Male',
        maritalStatus: 'Single',
        children: '0',
        residenceType: 'Apartment',
        educationLevel: 'PhD',
        employmentStatus: 'Self-Employed',
        sector: 'Research',
        durationEmployment: '5 years',
        officeEmail: 'alan.turing@crypto.org',
        monthlyIncome: '₦600,000 - ₦900,000',
        loanRepayment: 20000,
        savings: 300000,
        twitter: '@alanturing',
        facebook: 'facebook.com/alan.turing',
        instagram: '@alanturing',
        guarantors: [
            {
                fullName: 'Max Newman',
                phoneNumber: '+1-555-4567',
                email: 'max.newman@example.com',
                relationship: 'Mentor',
            },
        ],
        tier: 1,
        balance: 150000,
        bank: 'Global Trust Bank',
        accountNumber: 1123581321,
        bankId: 'GTB003',
        status: 'Pending',
        organization: 'Crypto Research Institute',
        username: 'aturing',
        dateJoined: '2024-01-10T14:45:20Z',
    },
];
